#!/usr/bin/env bash

# No x as we don't want to see the commands
set -euo pipefail

BRANCH=`git branch --show-current`

if [[ "$BRANCH" =~ ^(master|main)$ ]]; then
  echo
  echo "Prevented pushing to $BRANCH. Use --no-verify to bypass this pre-push hook."
  echo
  exit 1
fi

exit 0
